Devrel 1160/update boilerplate
kontent-ai/migrations-boilerplate pull request #23
Opened 2024-07-11 12:07 UTC by IvanKiral

### Motivation

Which issue does this fix? Fixes #`issue number`

If no issue exists, what is the fix or new feature? Were there any reasons to fix/implement things that are not obvious?

### Checklist

- [ ] Code follows coding conventions held in this repo
- [ ] Automated tests have been added
- [ ] Tests are passing
- [ ] Docs have been updated (if applicable)
- [ ] Temporary settings (e.g. variables used during development and testing) have been reverted to defaults

### How to test

If manual testing is required, what are the steps?

2024-08-14 14:00 UTC, JiriLojda requested changes

2024-08-21 06:39 UTC, IvanKiral commented on src/08_updateType.ts
> +    // Using Catch to be able to rollback even partial migrations.
it was a catch that there is no catch

2024-08-26 12:34 UTC, JiriLojda commented on package.json
> +    "lint-staged": "^15.2.7",
There is still the configuration in `package.json`.

2024-08-26 13:00 UTC, JiriLojda approved these changes

2024-08-27 06:48 UTC, merged